config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'customers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :admins, only: [:index, :edit, :show]
  resources :customers

  get '/gallery_addresses', to: 'application#gallery_web_address'

  root to: "customers#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def full_name
    first_name + ' ' + last_name
  end

  def customer_attributes
    attributes.except('id', 'created_at', 'updated_at')
  end

  def web_page_viewable?
    web_page_viewable
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery except: :gallery_web_address

  def gallery_web_address
    @customers = Customer.all
                  .where(web_page_viewable: true)
                  .map { |c| { name: c.note, gallery_web_address: c.gallery_web_address } }

    respond_to do |format|
      format.js { render json: @customers, callback: params['callback'] }
      format.json { render json: @customers }
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "You've successfully edited customer's profile!"
      redirect_to customer_path(@customer)
    else
      flash[:alert] = "Uh oh, something went wrong :("
      redirect_to edit_customer_path(@customer)
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = "You've created a new customer!"
      redirect_to customers_path
    else
      flash[:alert] = "Uh oh, something went wrong :("
      render "new"
    end
  end

  def destroy
  end

  private

  def customer_params
    params.require(:customer).permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/edit.html.erb
<div class="clearfix">
  <h1 class="float-left">Edit Customer Information</h1>
  <%= link_to 'Go Back To Customer Page', customer_path(@customer), class: "float-right btn btn-lg btn-info add-customer-btn" %>
</div>

<%= simple_form_for :customer, url: customer_path(@customer), method: :patch do |c| %>
  <%= c.input :first_name, error: "Username is required" %>
  <%= c.input :last_name %>
  <%= c.input :email %>
  <%= c.input :gallery_web_address %>
  <%= c.input :phone %>
  <%= c.input :address %>
  <%= c.input :event_date %>
  <%= c.input :event_location %>
  <%= c.input :note %>
  <%= c.input :web_page_viewable, as: :boolean %>
  <%= c.button :submit, "Save Changes To Customer Profile", class: "width-100 btn btn-primary" %>
<% end %>

app/views/customers/index.html.erb
  <h1 class="float-left">Client List</h1>

  <%= link_to "Add New Client", new_customer_path, class: "float-right btn btn-lg btn-primary add-customer-btn" %>



<table class="customers--table">
  <tr>
    <th>Full Name</th>
    <th>Gallery Web Address</th>
    <th>Allow web address to be viewed?</th>
  </tr>
  <% @customers.each do |customer| %>
    <tr>
      <td>
        <%= link_to customer.full_name, customer_path(customer) %>
      </td>
      <td><%= customer.gallery_web_address %></td>
      <td><%= customer.web_page_viewable? %></td>
    </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
<h1>Add New Customer</h1>

<%= simple_form_for @customer do |c| %>
  <%= c.input :first_name %>
  <%= c.input :last_name %>
  <%= c.input :email %>
  <%= c.input :gallery_web_address %>
  <%= c.input :phone %>
  <%= c.input :address %>
  <%= c.input :event_date %>
  <%= c.input :event_location %>
  <%= c.input :note %>
  <%= c.input_field :web_page_viewable,  as: :boolean %>
  <%= c.label :web_page_viewable %>
  <%= c.button :submit, "Create Client", class: "btn btn-primary width-100" %>
<% end %>

<script type="text/javascript">
  var target = $("[name='customer[web_page_viewable]']")[0];
  target.remove();
  $("[name='customer[web_page_viewable]']").bootstrapSwitch();
</script>

app/views/customers/show.html.erb
<h1 class="float-left">Customer Information</h1>

<%= link_to "Edit Customer", edit_customer_path, class: "float-right btn btn-lg btn-primary add-customer-btn" %>

<table class="customers--table">
  <% @customer.customer_attributes.each do |k,v| %>
    <tr>
      <td><%= k.gsub(/_/, ' ').titleize %></td>
      <td><%= v %></td>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<h1>Welcome Photostache Team!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photostache</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to "Photostache", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if admin_signed_in? %>
            <ul class="nav navbar-nav">
              <li class="active">
                <%= link_to 'Client Information', customers_path %>
              </li>
              <!-- <li><a href="#">Link</a></li> -->
            </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li><%= link_to 'Sign Out', destroy_admin_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Login', new_admin_session_path %></li>
            <% end %>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert"><%= notice %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible" role="alert"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>


  </body>
</html>